### ISSUE TITLE
memory leak with unstable connections from peers 

### ISSUE THREAD

**Issue by ewagmig** [lucas-clemente/quic-go#2393]
Hi there,
  As previous issue #2336, we have witnessed memory leaks eventually as result of memory exhaustion. This issue is the case with current version `v0.14.3`
However, the connection from the peers in our testing environment **is not so stable**, and here is the log on this circumstances:
```
ERROR[2020-02-27|16:28:17.855+0800|] p2p/server.go:975                         Failed RLPx handshake                    addr=120.212.132.110:32901                      conn=dyndial err="AcceptStream net io.reader timeout"
INFO [2020-02-27|16:28:17.855+0800|] p2p/server.go:951                         Setting up connection failed             addr=120.212.132.110:32901                      err="AcceptStream net io.reader timeout"
INFO [2020-02-27|16:28:17.855+0800|] p2p/dial.go:310                           Dial error                               task="dyndial 70d8c54d2dcc4d49 120.212.132.110:32901" err="AcceptStream net io.reader timeout"
INFO [2020-02-27|16:28:30.546+0800|] consensus/ucon/timer_mgr.go:376           Timer: time out.                         Round=194587 RoundIndex=682  MaxRoundIndex=682
INFO [2020-02-27|16:28:57.585+0800|] consensus/ucon/timer_mgr.go:376           Timer: time out.                         Round=194587 RoundIndex=683  MaxRoundIndex=683
INFO [2020-02-27|16:29:24.566+0800|] consensus/ucon/timer_mgr.go:376           Timer: time out.                         Round=194587 RoundIndex=684  MaxRoundIndex=684
ERROR[2020-02-27|16:29:47.568+0800|] p2p/server.go:975                         Failed RLPx handshake                    addr=120.212.132.110:32901                      conn=dyndial err="AcceptStream net io.reader timeout"
INFO [2020-02-27|16:29:47.568+0800|] p2p/server.go:951                         Setting up connection failed             addr=120.212.132.110:32901                      err="AcceptStream net io.reader timeout"
INFO [2020-02-27|16:29:47.568+0800|] p2p/dial.go:310                           Dial error                               task="dyndial 70d8c54d2dcc4d49 120.212.132.110:32901" err="AcceptStream net io.reader timeout"
```
The memory used ramp up quickly and only one day later the total memory consumption is merely 3G. 
Here is the `pprof` heap statistics:
```
Showing top 10 nodes out of 212
      flat  flat%   sum%        cum   cum%
     388MB 13.74% 13.74%      388MB 13.74%  github.com/syndtr/goleveldb/leveldb/memdb.New
  312.33MB 11.06% 24.79%   329.33MB 11.66%  github.com/lucas-clemente/quic-go.(*session).postSetup
  249.36MB  8.83% 33.62%   249.36MB  8.83%  github.com/lucas-clemente/quic-go.init.0.func1
  238.95MB  8.46% 42.08%   238.95MB  8.46%  github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).Get
  141.77MB  5.02% 47.10%   167.78MB  5.94%  github.com/lucas-clemente/quic-go/internal/handshake.newCryptoSetup
  138.52MB  4.90% 52.01%   138.52MB  4.90%  crypto/aes.newCipher
  127.52MB  4.51% 56.52%   127.52MB  4.51%  reflect.New
  125.01MB  4.43% 60.95%   125.01MB  4.43%  math/big.nat.make
  122.50MB  4.34% 65.28%   261.01MB  9.24%  gitlab.iyouchain.com/youchain/go-youchain/rlp.decodeBigInt
   92.03MB  3.26% 68.54%    92.03MB  3.26%  crypto/aes.(*aesCipherGCM).NewGCM
```
Below is the heap profile on the testing node:
[pprof.you-linux-amd64.alloc_objects.alloc_space.inuse_objects.inuse_space.033.pb.gz](https://github.com/lucas-clemente/quic-go/files/4261974/pprof.you-linux-amd64.alloc_objects.alloc_space.inuse_objects.inuse_space.033.pb.gz)

This is quite similar to the situation of previous issue on version `v0.11.1`. So could you please help to watch on this scenario:  what is the performance of quic when handling **unstable** connection from neighbored peers?

**Comment by marten-seemann** [comment]
When such an error occurs, do you release all resources associated with this session? It's important that you don't hold any pointer to the `Session`, as well as to any of the streams you might have opened on or accepted from that session. Otherwise the GC can't garbage collect the session.

**Comment by ewagmig** [comment]
Hi @marten-seemann, thanks for your instant feedback. This case reoccurrence was based on the scenarios when some peers with poor connection, i.e. this poor peers were in the DHT table after node discovery, however, the handshake between peers were not established at all. 
Per the implementation of quic-go to the `session`, is there any best practice on it? We have obeyed the original guide on it, but not know whether it is updated since then. The code path could be seen from the `pprof` profile.

**Comment by marten-seemann** [comment]
> The code path could be seen from the pprof profile.

Which pprof command are you running to see that?

**Comment by marten-seemann** [comment]
> This case reoccurrence was based on the scenarios when some peers with poor connection, i.e. these poor peers were in the DHT table after node discovery, however, the handshake between peers were not established at all.
Per the implementation of quic-go to the session, is there any best practice on it? 

`quic.Dial` won't return before the QUIC handshake completes. So I guess the problem occurs with connections that have been establish and then fail for some reason (maybe a connection timeout).

**Comment by ewagmig** [comment]
Hi @marten-seemann : please first unzip the .gz file attached above. Then you can use the `pprof` tool as below example:
`go tool pprof -http ":8848" pprof.you-linux-amd64.alloc_objects.alloc_space.inuse_objects.inuse_space.032.pb`

**Comment by marten-seemann** [comment]
Thank you @ewagmig.

I'm wondering, which version of quic-go are you using. `session.postSetup` was removed in https://github.com/lucas-clemente/quic-go/pull/2185, some time between v0.12.1 and v0.13.0, and not introduced since. So it looks like you're running v0.12.1 or earlier.

**Comment by ewagmig** [comment]
Hi @marten-seemann, thanks for your feedback. We will double check the quic version we are using. 
Will come to you later~

**Comment by ewagmig** [comment]
> > This case reoccurrence was based on the scenarios when some peers with poor connection, i.e. these poor peers were in the DHT table after node discovery, however, the handshake between peers were not established at all.
> > Per the implementation of quic-go to the session, is there any best practice on it?
> 
> `quic.Dial` won't return before the QUIC handshake completes. So I guess the problem occurs with connections that have been establish and then fail for some reason (maybe a connection timeout).

Hi, @marten-seemann this clue is quite important to us with current scenario:
1) the `enchandshake` has already been established
2) the following protocol handshake failed due to some reason, just like this log from the testing node:
![image](https://user-images.githubusercontent.com/37991051/75600135-c3ab9000-5ae6-11ea-8547-19a6cf4dd885.png)

So I'm wondering how quic handle on this situation, or what step should be emphasized to prevent this connection from continuing?

**Comment by marten-seemann** [comment]
I don’t see any quic-go error message in this screenshot.

**Comment by ewagmig** [comment]
Yes, there were no error messages from this screenshot printing the `proto handshake` phase error. There is no relation with the quic. I was just  recalled with what you mentioned on the `quic.Dial` return mechanism. 
We have deployed testing node with older version by mistake and replaced the one with version `v0.14.3`. The testing scenario keeps the same and until now everything goes well. 
We will keep watching the new `quic` performance against such poor connection.

**Comment by ewagmig** [comment]
Hi @marten-seemann We have replaced the quic version with latest one, i.e. `v0.14.4` and run the testing nodes under previous connection environment. 2 days have passed and there was no outstanding proof on `quic`. 
Here is the `pprof` from latest `quic` version, F.Y.I.
[pprof.you-linux-amd64.alloc_objects.alloc_space.inuse_objects.inuse_space.042.pb.gz](https://github.com/lucas-clemente/quic-go/files/4284646/pprof.you-linux-amd64.alloc_objects.alloc_space.inuse_objects.inuse_space.042.pb.gz)
Hope this could give positive feedback on `quic` handling connection.

**Comment by marten-seemann** [comment]
Happy to hear that the memory leak has apparently been fixed! Thanks for reporting!

**Comment by raszia** [comment]
@marten-seemann ,  I would like to reopen this issue.

I would like to mention that I am still experiencing the same issue described in this closed issue.
Despite the closure of the issue, I have encountered the memory leak problem consistently. I have not been able to find a resolution or workaround for it yet.

I kindly request reopening the issue or providing further guidance on how to address this persistent memory leak. Any assistance or insight into this matter would be greatly appreciated.

Thank you for your attention and support.
I have used version 0.35.1 of the codebase.
```
File: webService.run
Build ID: 046cd5ef5de1f12c5d4b70dbb96ebafb3be85a33
Type: inuse_space
Time: Jun 3, 2023 at 4:22pm (+0330)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) web
(pprof) top
Showing nodes accounting for 388.27MB, 86.67% of 447.98MB total
Dropped 194 nodes (cum <= 2.24MB)
Showing top 10 nodes out of 116
      flat  flat%   sum%        cum   cum%
  201.79MB 45.04% 45.04%   201.79MB 45.04%  github.com/quic-go/quic-go.init.0.func1
   58.38MB 13.03% 58.08%    58.38MB 13.03%  github.com/webservice/utility.ReadHTTPDataBodyResponse
   32.08MB  7.16% 65.24%    32.08MB  7.16%  github.com/smallnest/goframe.(*lengthFieldBasedFrameConn).ReadFrame
   29.01MB  6.48% 71.71%    30.01MB  6.70%  github.com/quic-go/quic-go.newConn
   15.77MB  3.52% 75.23%    15.77MB  3.52%  regexp.(*Regexp).get
   13.22MB  2.95% 78.18%    15.36MB  3.43%  compress/flate.NewWriter
   11.50MB  2.57% 80.75%    11.50MB  2.57%  runtime.malg
   11.50MB  2.57% 83.32%    11.50MB  2.57%  golang.org/x/net/internal/socket.(*mmsghdrsPacker).prepare
    8.01MB  1.79% 85.11%     8.01MB  1.79%  runtime.allocm
       7MB  1.56% 86.67%    41.27MB  9.21%  github.com/quic-go/quic-go.(*Transport).init.func1
```

**Comment by marten-seemann** [comment]
Please open a new issue if you think you’ve found a bug. We’d need a few more infos though to actually debug this. It’s expected that a sync.Pool would hold some memory, that’s that it’s there for.
